################################################################################################
## Debian Packages
################################################################################################

# Packages to be Installed
debian_packages:
  - curl
  - git
  - make
  - neofetch
  - neovim
  - python3-pip
  - ufw
  - unzip

firewall_ports:
  - 22