---
- name: Enable Firewall and Setup Rules Debian
  become: yes
  block:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        default: deny

    - name: Set logging
      community.general.ufw:
        logging: 'on'

    - name: Create OpenSSH connection rate limiting rule
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Add ports to firewall
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ firewall_ports }}"

  when: ansible_os_family == "Debian"

- name: Enable Firewall and Setup Rules RedHat
  become: yes
  block:
    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add ports to firewall
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ firewall_ports }}"
  when: ansible_os_family == "RedHat"
...