---
- name: Update sshd_config for Linux Servers
  tags: base, users
  become: yes
  ansible.builtin.template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root 
    group: root 
    mode: '0600'
    validate: '/usr/sbin/sshd -T -f %s'
    backup: yes
  notify: restart_sshd
...