---
- name: Verify if Banner exists
  ansible.builtin.stat: 
    path: /etc/update-motd.d/00-custom
  register: motd_present

- name: Set New Banner
  block:
    - name: Delete Original update-motd Files
      ansible.builtin.file:
        path: "/home/{{ user }}/motd_backup/"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Backup Original motd-update Files
      ansible.builtin.copy: 
        remote_src: true
        src: "/etc/update-motd.d/{{ item }}"
        dest: "/home/{{ user }}/motd_backup/"
        owner: "{{ user }}"
        group: "{{ user }}"
      ignore_errors: yes
      loop:
        - 00-header
        - 10-help-text
        - 50-motd-news
        - 50-landscape-sysinfo
        - 90-updates-available
        - 91-contract-ua-esm-status
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 95-hwe-eol
        - 97-overlayroot
        - 98-fsck-at-reboot
        - 98-reboot-required

    - name: Delete Original update-motd Files
      ansible.builtin.file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      ignore_errors: yes
      loop:
        - 00-header
        - 10-help-text
        - 50-motd-news
        - 50-landscape-sysinfo
        - 90-updates-available
        - 91-contract-ua-esm-status
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 95-hwe-eol
        - 97-overlayroot
        - 98-fsck-at-reboot
        - 98-reboot-required

    - name: Update Banner for Linux Servers
      ansible.builtin.template: 
        src: 00_custom.j2
        dest: /etc/update-motd.d/00-custom
        owner: root 
        group: root 
        mode: '0755'
  when: motd_present.stat.exists is false
...